apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 
  selector:
    app: postgres