apiVersion: v1
kind: PersistentVolume 
metadata:
  name: postgresql-data 
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume" # Sets the volume's path