apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgresql-data-claim 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size